name: audio_2_audio_file_translator
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  aws_polly_api: ^2.0.0
  file_picker: ^5.0.1
  path_provider: ^2.0.9
  shared_preferences: ^2.2.3
  http_parser: ^4.0.2
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  ffmpeg_cli: ^0.2.0
  flutter_dotenv: ^5.0.2
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - test/test_samples/short_speech.mp3
    - test/test_samples/short_transcription_list.yaml
    - test/test_samples/short_translation.txt
    - test/test_samples/long_complex_speech.mp3
    - test/test_samples/long_complex_transcription_list.yaml
    - test/test_samples/long_complex_translation.txt